Fix Par Monad example test failure
With the ParMonad / "testing exposes a deadlock" / randomly test,
simplification threw an error:

    Exception: (dejafu) Got a different result after simplifying:
    'True' /= 'Abort'

This is failing even with previously supported versions of GHC, so I
think it's a new library version (probably random, giving an original
trace which exposes the bug).

Disabling "safe IO" for this test fixes it, which means that either
the IO is not safe after all, or that there's another bug elsewhere
which is being hidden now that simplification is more
restricted... however, none of the other tests are failing, so I hope
it's just the IO.